### ISSUE TITLE
Fork: moved media_player, media_renderer and JW Player stuff to local_jwplayer

### ISSUE THREAD

**Issue by jojoob** [lucisgit/moodle-filter_jwplayer#11]
Hello,
just want to ask you to check out my fork.

I used the *filter_jwplayer_media* class to create my own *core_media_renderer* subclass to override this renderer in a theme in the past (to use JW Player also when embedding file resources (mod_resource), also discussed in #2). And now I'm currently working on a video activity plugin (https://github.com/sudile/moodle-mod_video) where I also want to use the *filter_jwplayer_media* class.

To not depend on the filter plugin I have moved the media_player, media_renderer and jw player stuff (incl. settings) to a new local plugin (https://github.com/sudile/moodle-local_jwplayer). (And added support for subtitle tracks.)

And at last I have forked the filter plugin (https://github.com/sudile/moodle-filter_jwplayer) and adjusted it to work with the local_jwplayer plugin.

What do you think, is this something that could be pushed back?

**Comment by kabalin** [comment]
Hi, Johannes! Just had a look through your code. One thing I definitely like is that you embedded download button setup in the single JS init call, I was thinking about doing the same while worked on RTMP support in the last few days (see master updates). If you could push that as a separate patch - that would be great.

Regarding local_jwplayer. If I have got it right, the idea is to detach player from the filter and use player in other areas irrespective of whether filer is installed - is that right?

It is a pity that core_media_player does not have a separate plugins infrastructure, it would be nice to have every item that extends core_media_player be presented as a separate plugin and then used from anywhere (e.g. filters, mods, etc.), which would allow an easy way of "ranking" players as well. May be it is something worth discussiong with community.

I like the idea of maintaining a player separately, but I do not think that suggesting people to install two plugins (local_jwplayer, filter_jwplayer) instead of one is a good idea either. In fact, filter_jwplayer_media and filter_jwplayer_renderer calsses from the filter can be used anywhere outside filter (assuming the filter is installed, it does not even need to be enabled). There is also a way to  make sure that filter is installed if some other plugin need, see $plugin->dependencies in version.php (https://docs.moodle.org/dev/version.php). So, for now I think it would be reasonable to maintain just one filter plugin containing both filter and player (as that probably what most people need). One could reuse player classes anywhere they are needed, it should not cause issues, because disabling filter (in case it is not needed) will not stop player from working in other places, so filter may act as pure "player" plugin - the advantage however will be that less plugins to install. If some development of core media infrastructure will happen in future, player may move out to "players", in which case "filter" might not be required at all, as embedding of JW Player will be handled by core media filter instead.

**Comment by jojoob** [comment]
> If I have got it right, the idea is to detach player from the filter and use player in other areas irrespective of whether filer is installed - is that right?

yes, correct.

I also think a plugin type like "media_" or "player_" would be very nice. And I agree with you that have to install two plugins (local_jwplayer and filter_jwplayer) is not a great option.

Do you think it's a good idea to implement additional features which could actually not be used within the filter but could be useful for other plugins depend on filter_jwplayer? Like the subtitles support I've added in local_jwplayer (you can add subtitle tracks via the option parameter). I also think about a custom player id option and adding additional custom buttons.

**Comment by kabalin** [comment]
I think adding additional features to player itself is possible. As long as they are not clashing with the main functionality (in case of option parameter they should not cause issues), it is OK to add anything useful. Feel free to create a pull request for subtitles ;-)

**Comment by jojoob** [comment]
OK, I will think about it while working on the mentioned mod_video plugin and maybe integrate the changes directly in the filter plugin and create a pull requests. :)
