### ISSUE TITLE
Player is left justified

### ISSUE THREAD

**Issue by fernandooliveira** [lucisgit/moodle-filter_jwplayer#3]
Currently, the filter does't take into account the position of the media link (left, centre, right); it's always left-justified. Can this be fixed?

Thanks for putting this together. Very handy!

**Comment by kabalin** [comment]
Hello, thanks for reporting. It does not seem an easy way to make it respect alignment. Basically because player is inserted outside the actual <a> link wrapper, it does not take into account the link positioning. Besides, it seems complicated to make it respect "text-align" properly. I will see what can be done.

**Comment by owenbarritt** [comment]
Looking at this it looks as if the original media filter replaced the <a> tag and kept any tags around it which then allowed for centering, etc.

The JWPlayer filter places the player div outside the original tags, so loses any styling from them.

**Comment by kabalin** [comment]
@owenbarritt, thanks for looking into this.
